feat: updated CMakeLists.txt
atsign-foundation/uuid4 pull request #3
Opened 2024-08-26 15:17 UTC by JeremyTubongbanua

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

2024-08-26 18:46 UTC, JeremyTubongbanua commented
Upon approval, we should:

1. Make a `v1.0.3` release
2. Update `at_c/packages/atchops` dependency to use the new release

2024-08-26 18:52 UTC, JeremyTubongbanua commented
Putting back to draft. I want to first add `idf_component.yml`

2024-08-27 12:56 UTC, JeremyTubongbanua commented
Ready for review

2024-08-27 13:09 UTC, realvarx commented
LGTM

2024-08-28 09:00 UTC, cpswan approved these changes

2024-08-28 09:02 UTC, cpswan requested changes

2024-08-28 09:02 UTC, cpswan commented on idf_component.yml
> +license: "BSD-3-Clause"
The license we have for this repo (inherited from upstream) is a MIT license

2024-08-28 15:22 UTC, JeremyTubongbanua commented on idf_component.yml
> +license: "BSD-3-Clause"
https://github.com/atsign-foundation/uuid4/pull/3/commits/8672adee125fa243e2f683bd6cef6b887017bc7f

2024-08-28 16:17 UTC, cpswan approved these changes

2024-08-28 23:08 UTC, merged